### ISSUE TITLE
Unable to use wasync

### ISSUE THREAD

**Issue by vusarath** [Atmosphere/wasync#116]
Hi 
I am running it on Android ADT eclipse 
I created the 
AtmosphereClient client = (AtmosphereClient)ClientFactory.getDefault().newClient(AtmosphereClient.class);
RequestBuilder request = client.newRequestBuilder().method(METHOD.GET)....

final org.atmosphere.wasync.Socket socket = client.create();

java.lang.IllegalStateException: java.lang.ClassNotFoundException: Didn't find class "sun.security.util.HostnameChecker" on path: DexPathList[[zip file "/data/app/com.example.atmosphere-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.atmosphere-1, /vendor/lib, /system/lib]]

exception arises  

can you explain me the step to integrate the wasync jar in eclipse
i only used the wasync jar "wasync-2.0.0.jar" and "wasync-2.0.0-all.jar"
but unble to run since it throws the same error

Thanks for helping

**Comment by slandelle** [comment]
Upgrade AHC 1.9.10

**Comment by vusarath** [comment]
Still same problem
