### ISSUE TITLE
Upgrade wasync's async-http-client dependency.

### ISSUE THREAD

**Issue by thabach** [Atmosphere/wasync#126]
The latest async-http-client version (1.9.18) contains important fixes for spurious timeouts (in the HTTPProtocol class, see here https://github.com/AsyncHttpClient/async-http-client/issues/848).

**Comment by jfarcand** [comment]
Bumped with new release today https://github.com/Atmosphere/wasync/commit/590de884eb1002d34112d526d0067efa4b8b2d87
