### ISSUE TITLE
Very small doc issue

### ISSUE THREAD

**Issue by supertick** [Atmosphere/wasync#134]
Latest release has the following example :

  socket.on(new Function<Reader>() {
                @Override
                public void on(Reader r) {
                    // Read the response
                }
            }).on(new Function<IOException>() {

```
            @Override
            public void on(Throwable t) {
                // Some IOException occurred
            }
```

Looks like the interface was changed to 
    @Override
         public void on(IOException arg0) { 
         }

Cheers !

**Comment by jfarcand** [comment]
@supertick Link to the error? Thanks!

**Comment by supertick** [comment]
https://github.com/Atmosphere/wasync 

example - starts with "As simple as"

**Comment by thabach** [comment]
@supertick correct with 07d2a783c1473330dcc50588ae69d409c3110e7c - thx !
