### ISSUE TITLE
Issue using wasync library  in android 4.2.2

### ISSUE THREAD

**Issue by nagabharat** [Atmosphere/wasync#138]
got this exception while using wasync in android 4.2.2
06-09 05:02:28.081 1659-1659/? W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/ning/http/client/AsyncHttpClient;
06-09 05:02:28.081 1659-1659/? W/System.err: java.lang.ExceptionInInitializerError
06-09 05:02:28.091 1659-1659/? W/System.err:     at com.synycs.truckway.wAsyncChat.onCreate(wAsyncChat.java:151)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.app.Activity.performCreate(Activity.java:5104)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.app.ActivityThread.access$600(ActivityThread.java:141)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
06-09 05:02:28.091 1659-1659/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
06-09 05:02:28.099 1659-1659/? W/System.err:     at android.os.Looper.loop(Looper.java:137)
06-09 05:02:28.099 1659-1659/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5041)
06-09 05:02:28.099 1659-1659/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
06-09 05:02:28.099 1659-1659/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:511)
06-09 05:02:28.099 1659-1659/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
06-09 05:02:28.099 1659-1659/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
06-09 05:02:28.099 1659-1659/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
06-09 05:02:28.099 1659-1659/? W/System.err: Caused by: java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory
06-09 05:02:28.119 1659-1659/? W/System.err:     at com.ning.http.client.AsyncHttpClient.<clinit>(AsyncHttpClient.java:152)
06-09 05:02:28.119 1659-1659/? W/System.err:    ... 15 more
06-09 05:02:28.149 1342-1353/? E/ActivityThread: Failed to find provider info for com.android.inputmethod.latin.dictionarypack
06-09 05:02:28.149 1342-1353/? E/BinaryDictionaryGetter: Could not find a dictionary pack
06-09 05:02:28.189 794-902/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property

**Comment by thabach** [comment]
@nagabharat please consult AsyncHttpClient/async-http-client#849
