### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by supertick** [Atmosphere/wasync#146]
@ https://github.com/Atmosphere/wasync/wiki/Getting-Started-with-wAsync 

Putting all together: a Chat Client

The code below demonstrates how to write a Chat application using the Atmosphere Framework. For the server side component, see the sample
--------------------------------------------------------------------------------------------------------------
"sample" (https://github.com/Atmosphere/wasync/tree/master/samples)  is a 404 error
perhaps it should be linked to 

https://github.com/Atmosphere/atmosphere-samples/tree/master/wasync-samples

**Comment by slovdahl** [comment]
Thank you, fixed!
