### ISSUE TITLE
Nullpointer exception in atmosphere runtime 2.0.3 version

### ISSUE THREAD

**Issue by Kamalakannan1981** [Atmosphere/wasync#160]
During tomcat server startup, I'm getting runtime exception after atomsphere framework started.

at org.atmosphere.cpr.AtmosphereResponse.setHeader(AtmosphereResponse.java:309)

The error is weird and getting this error all of sudden in Tomcat7.0.75.0 version.
JDK version 1.8.0_172
It was working in test region for last couple of years and quite surprised with this error now.
Could you please help to identify the rootcause of the issue?
Appreciate if someone could help to resolve it at earliest

**Comment by jfarcand** [comment]
Wrong place
